<?php

/**
 * Implement hook_uninstall.
 *
 * Disables and uninstalls os2forms_server_communication module.
 */
function os2forms_backend_uninstall() {
  if (module_exists('os2forms_server_communication')) {
    module_disable(array('os2forms_server_communication'));
    drupal_uninstall_modules(array('os2forms_server_communication'));
  }
  else {
    drupal_uninstall_modules(array('os2forms_server_communication'));
  }
}
